[project]
name = "databricks-delta-lake"
version = "0.1.0"
description = "Projeto Delta Lake no Databricks"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "pyspark>=3.5.0",
    "delta-spark>=3.2.0"
]
